### ISSUE TITLE
/ran parser - include what number was randomed

### ISSUE THREAD

**Issue by Kritoris** [smasherprog/EqTool#125]
Got to user the random parser today for the open zlandi.

Worked great but the tool doesn't list how much the roller rolled.

Eg. Did they /ran 32000 like they were supposed to or did they /ran 39000 to try get a higher number?

Not bad for group content, but for 170 people, validating what they rolled is hard....

**Comment by smasherprog** [comment]
I was at the zland raid too and I am making changes now.
In response to your above comment,  that isnt possible because each Section header has the random value.  So, if someone rolls  again it would put them into a different group with that number in it.

Below is what is going to go out soon. In below example the winner is Vasanle with a 292. The (#NUMBER) next to the name is the ORDER of that persons roll. 

So, Sanare is number 1 on the FOURTH roll, so it shouldnt count. Whitewhich is in second place, but its the 5th roll so, it shouldnt count.

<img width="328" alt="update1" src="https://github.com/smasherprog/EqTool/assets/3393733/11e557cc-26ee-4b2b-963a-646be7cff911">


ALL rolls will show, duplicates as well, but the ORDER of the roll can be seen. I hope this will help out.

**Comment by smasherprog** [comment]
It might be easier to simple not allow duplicates as well, but duplicate rolls are going to be the outlier, so there generally shouldnt be any duplicate rolls.

**Comment by smasherprog** [comment]
Changes pushed

**Comment by Kritoris** [comment]
Hey that looks like it fixes a problem I didn't even think about (someone rolling multiple times).

The concern I raised was more if they used the weobg number to roll.

Eg instead of rolling /ran 32000. They rolled \ran 37009.

The parser only shows the result of the roll '3567', not the value they rolled out of, so 3567\37000.

Make sense?

**Comment by smasherprog** [comment]
So I ignore any random that doesn't start at 0.  Give it a shot and try to do a random from none zero

**Comment by smasherprog** [comment]
Shouldn't show up at all unless it's from 0 to NUMBER

**Comment by smasherprog** [comment]
I need to do videos on how all of this stuff works.  There so much built in that is hard to see.

**Comment by smasherprog** [comment]
Let me know if the current changes work. Gonna close this. Please reopen if there are issues or if u can think of a better implementation.
